### PR TITLE
Add outer json wrapper to response

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by heuermh** [comment]
Hold on, Bob, I was about to give you more than one option!

**Comment by bmilius-nmdp** [comment]
Oops, too late.

bob

**Comment by bmilius-nmdp** [comment]
Not sure how to undo  a merge.

What are my other options?

Bob

**Comment by heuermh** [comment]
Compare to #232.

**Comment by bmilius-nmdp** [comment]
Yeah, I think you're right.
Basically one json object with key:values separated by commas inside. Right?

Bob

**Comment by heuermh** [comment]
#232 should return responses like
```json
{
  "sourceNamespace": "",
  "sourceUri": "",
  "targetNamespace": "",
  "targetUri": ""
}
```

**Comment by bmilius-nmdp** [comment]
Thanks!

**Pull request merged**
